### ISSUE TITLE
Does not install on PHP 8.1

### ISSUE THREAD

**Issue by tejasgosai88** [selective-php/archive-bomb-scanner#13]
When I try to install this dependency I get composer error. 
` - selective/archive-bomb-scanner 1.1.0 requires php ^7.2 which does not match your installed version 8.1.5.`

I checked composer.json for this library, should it have php >= 7.2 ?

**Comment by odan** [comment]
We have just published v2. Please try it again.

**Comment by tejasgosai88** [comment]
Thank you. It was installed without any issues.
