### ISSUE TITLE
[feature] Adding other archive Bomb Engines

### ISSUE THREAD

**Issue by peter279k** [selective-php/archive-bomb-scanner#2]
As title, It has other archive bombs.

And this issue should be considered and implemented.

## References
- https://github.com/bones-codes/bombs/tree/master/archives

**Comment by odan** [comment]
**Notice**: I have tested the current version 0.1.0 against all ZIP files from this github repo:
https://github.com/bones-codes/bombs/tree/master/archives

Result: 100% matches 👍 

But, because of the filesize of all ZIP files (124 MB) I will not commit this files into this repo.

**Comment by peter279k** [comment]
@odan, thanks for your effort :muscle: !

That's right. These archive files should not be under the Git version control because of large file sizes.

And I think we can consider following approaches:

- Using Git hook to download these large archive files in the `tests/files` folder during `git clone` command.
- Define the `composer` scripts to download these files if developers want to check them.
- Adding the `file lists` section in `README` to remind developers that we've already tested these bomb files :).

What do you think about this? And which one is our proper ways?

**Comment by odan** [comment]
I like the idea of using composer to download additional files from other repos.

We should still keep a small / minimal set of files within the tests/files directory.

But if somebody want's to test more he/she can call a composer command to download additional files.

For example: 
```
composer download-test-files
```

Calls a script like `php tests/download.php`

composer.json:

```json
"scripts": {
    "download-test-files": "php tests/download.php"
```

tests/download.php

```
<?php

// Download repos
exec ('git clone ...');
exec ('git clone ...');
// add more...

// copy files to /tests/files/zip/excluded
// ...

exit(0);
```

We also have to add an entry into `.gitignore` like

```
/tests/files/zip/excluded
```

**Comment by peter279k** [comment]
The download script is straightforward.

And I think we can consider another approach to implement `download` PHP script.

- Using the `curl_*`  function to download that archive bomb files.
- Copy the bomb archive files to the `/path/to/tests/files/zip/excluded` directory.

**Comment by odan** [comment]
I just created #7 for this feature.
