### ISSUE TITLE
Download additional archive files for unit-testing

### ISSUE THREAD

**Issue by odan** [selective-php/archive-bomb-scanner#7]
There is already a minimal set of archive files within the tests/files directory.

But if somebody want's to test more we could provide a composer command to download additional files from other repos.

### Repositories

* https://github.com/bones-codes/bombs/tree/master/archives

### Solution

Add a new composer script like:

```
composer download-test-files
```

Calls a script like `php tests/download.php`

composer.json:

```json
"scripts": {
    "download-test-files": "php tests/download.php"
```

Content of `tests/download.php`

```
<?php

// Download and copy the files to /tests/files/zip/excluded

file_put_contents('tests/files/zip/excluded/file.zip', file_get_content('https://url/to/file.zip'));
file_put_contents('tests/files/zip/excluded/file2.zip', file_get_content('https://url/to/file2.zip'));
// add more...

exit(0);
```

We also have to add an entry into `.gitignore` like

```
/tests/files/zip/excluded
```

**Comment by peter279k** [comment]
I think this `download` script is good, but I don't think using the `file_get_content` to fetch additional archive bomb files is security.

To let fetch archive files be security, I recommend we can consider using the [humbug/file_get_contents](https://github.com/humbug/file_get_contents) or `curl_*` functions instead.

**Comment by odan** [comment]
I don't see any real security benefit using `humbug/file_get_contents`. Then better use `curl_*` with enabled SSL check (`CURLOPT_SSL_VERIFYPEER => true`, `CURLOPT_SSL_VERIFYSTATUS` => true) to get a real security advantage.

**Comment by peter279k** [comment]
@odan, please look at the [FileGetContents.php](https://github.com/humbug/file_get_contents/blob/master/src/FileGetContents.php) class.

As you can see this class, it seems that this class enhance the `file_get_contents` function when sending a HTTP request.

Such as `HTTPS`, `TLS` and `SSL` support, headers set, and etc.

But I think it's fine to use `curl_*` functions to replace the original `file_get_contents` function.
